locales:
  en:
    name:        Plains Cree Keyboards
    description: Keyboards for Plains Cree, developed by the University of Alberta Language Technology Lab with tools developed at Giella Language Technologies.
author:       University of Alberta Language Technology Lab (ALTLab)
copyright:    (c) 2021 ALTLab
email:        21ct4il@gmail.com
organisation: University of Alberta
